---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.io
  resources:
  - downscalepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.io
  resources:
  - downscalepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - downscaler.io
  resources:
  - downscalepolicies/status
  verbs:
  - get
  - patch
  - update
